### ISSUE TITLE
User-friendly error message API hard to use through o.m.a.eclipse plugin

### ISSUE THREAD

**Issue by JoriDubrovin** [ModelDriven/Alf-Reference-Implementation#10]
I have not found a clean way to invoke `ConstraintViolation.loadErrorMessageFile`, which expects a file path, when the error message file is just a resource in the org.modeldriven.alf.eclipse plugin jar.  It is easy to get the error messages as an InputStream (`ConstraintViolation.class.getResourceAsStream(...)`), but there is no loadErrorMessageFile overload that accepts an InputStream.

**Comment by seidewitz** [comment]
Resolved in v0.6.0e, but left open pending potential additional revision to enhancement #1 for v1.0.0.

**Comment by seidewitz** [comment]
Resolved in v1.0.0.
