### ISSUE TITLE
Exception when the type of an association end is a use case

### ISSUE THREAD

**Issue by JoriDubrovin** [ModelDriven/Alf-Reference-Implementation#12]
When calling `org.modeldriven.alf.syntax.statements.Block.deriveAll` for parsed Alf statements, `org.modeldriven.alf.eclipse.uml.StructuralFeature.getType()` throws `ClassCastException` when the type of the feature is a `org.eclipse.uml2.uml.UseCase` (`org.modeldriven.alf.eclipse.uml.NamedElement` cannot be cast to `org.modeldriven.alf.uml.Type`).  Even though we are not trying to access this particular feature in Alf, the static checker ends up here through `org.modeldriven.alf.syntax.units.impl.NamespaceDefinitionImpl.resolveAssociationEnd`.

**Comment by seidewitz** [comment]
Jori,

Try v0.6.0f, currently the head revision.

Ed

**Comment by seidewitz** [comment]
Resolved in v0.6.0f.
