### ISSUE TITLE
JavaCC plug-in preferences include system-specific paths

### ISSUE THREAD

**Issue by abstratt** [ModelDriven/Alf-Reference-Implementation#81]
JavaCC plug-in preferences include system-specific paths. 
See https://github.com/ModelDriven/Alf-Reference-Implementation/blob/bf25909a928d15b0106a39904a5aaa289cef63d4/org.modeldriven.alf/.settings/sf.eclipse.javacc.prefs.

```
RUNTIME_JJJAR=/Applications/Eclipse 4.5.app/Contents/Eclipse/plugins/sf.eclipse.javacc_1.5.33/jars/javacc-6.0.jar
RUNTIME_JTBJAR=/Applications/eclipse/plugins/sf.eclipse.javacc_1.5.24/jtb-1.4.4.jar
```

 PR to follow.

**Comment by seidewitz** [comment]
Resolved in v1.1.0g.
