### ISSUE TITLE
Library files do not open with declared minimum version of Eclipse UML2

### ISSUE THREAD

**Issue by JoriDubrovin** [ModelDriven/Alf-Reference-Implementation#9]
The plugin org.modeldriven.alf.eclipse declares 4.0.2 as the minimum version of the org.eclipse.uml2[.resources] plugins from Eclipse UML2 project.  However, some files under [org.modeldriven.alf.eclipse/Libraries/uml](https://github.com/ModelDriven/Alf-Reference-Implementation/tree/master/org.modeldriven.alf.eclipse/Libraries/uml) do not seem to open with UML2 v4.0.2, in the sense that the returned EMF objects are not `org.eclipse.uml2.uml.Element`s.  They probably need version 5 or later, as indicated by `xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML"`.  Specifically, those files are Alf.library.uml, fUML.library.uml, and Standard.profile.uml.

**Comment by seidewitz** [comment]
Resolved in v0.6.0e.
